apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - common
resources:
  - bases/eventbridge.services.k8s.aws_archives.yaml
  - bases/eventbridge.services.k8s.aws_eventbuses.yaml
  - bases/eventbridge.services.k8s.aws_rules.yaml
